
development:
  adapter: postgresql
  database: reumanager_dev
  user:
  password:
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: reumanager_test
  user:
  password:
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: reumanager_prod
  user:
  password: 
  host: localhost
  pool: 5
  timeout: 5000
